# config/attack_config.yaml

seed: 43

attacker:
  type: steal_encoder
  query_access: encoder_query
  latent_access: noisy_scaled_z
  noise_scale: 0.8
  query_budget: 10000

  proxy_dataset:
    name: cifar100         # <--- 指定使用 CIFAR-100
    data_dir: ./data_cifar100 # <--- 指定 CIFAR-100 的路径
  # ---------------------------------

  surrogate_model:
    arch_name: resnet18
    latent_dim: 128

  training_attacker:
    lr: 0.001
    batch_size: 128
    epochs: 15
    query_batch_size: 256 # 这个 batch size 用于加载代理数据集